version: '3.1'
services:
  app:
    container_name: student-quarkus
    image: student-quarkus
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - some-postgres
  some-postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=student_data
